### ISSUE TITLE
Shall colorizing and timestamps be optional?

### ISSUE THREAD

**Issue by vi** [cardoe/stderrlog-rs#11]
Can `stderrlog` turn into an unbloated logger for small tools (yet with easy access to `--quiet` and `--verbose` modes) by disabling some Cargo features?

**Comment by cardoe** [comment]
This sounds like a great idea.

**Comment by cardoe** [comment]
Are you hoping to lose the dependency on `termcolor` entirely when built without the color feature or would something like https://docs.rs/termcolor/0.3.6/termcolor/struct.NoColor.html usage be good?

**Comment by cardoe** [comment]
Closing this due to lack of traction. I would welcome patches to achieve this if desired by folks.
