### ISSUE TITLE
Don't colorize if stderr is not a tty

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [cardoe/stderrlog-rs#14]
Currently even if using `ColorChoice::Auto`, stderrlog will use colors when piping to files, ex. `cargo run 2>&1 > log.txt`. This causes the log to have control characters in it, which is annoying and doesn't mirror what other unix tools do.

When using `ColorChoice::Auto`, stderrlog should check if stderr is a TTY (ex. by using the `isatty` crate) and disable colors if it isn't.

**Comment by nuxeh** [comment]
I've been doing this manually with the `atty` crate, thought at first that `stderrlog` might do this, but it's not a lot of code to pull it off manually.

**Comment by cardoe** [comment]
So looking at this, it will check every single time `log()` is called if its a tty or not. It seems like this check should happen once at the beginning and that's it.

**Comment by cardoe** [comment]
Tests fail because of https://github.com/rust-lang-nursery/log/issues/358
