### ISSUE TITLE
Raise MSRV from 1.16 to either 1.19, 1.21, or 1.31

### ISSUE THREAD

**Issue by vincentdephily** [cardoe/stderrlog-rs#22]
While trying to make a PR for #20, I had a lot of trouble trying to use rust 1.16:

* Cargo versions before `1.19.0` never finish generating `Cargo.lock`. Not sure what changed on crates.io since 1.19 was released, but this is a strong hint that rust 1.16 is no longer a good MSRV choice.
* In addition to pinning `cfg-if` to `0.1.9` as seen in `.travis.yml`, I needed to pin `unicode-segmentation` to `1.2.1` and `termcolor` to `1.0.x`.
* Even with those hurdles passed, tests only compile (and pass :)) starting with 1.21.0 due to structopt. The CI script doesn't run tests on 1.16.0, so I didn't persist looking for a version of structopt that works.
* The "out of the box MSRV" (letting cargo select whatever dep versions match Cargo.toml) is 1.31 (compile failures up to 1.24, and missing cargo features from 1.25 to 1.30).

Given all this, I suggest raising the MSRV at least to 1.21 (a MSRV without corresponding unittests is a pretty weak guarantee) or even to 1.31, which should future-proof things a bit and open up more refactoring opportunities, like switching to `edition=2018`.

**Comment by vincentdephily** [comment]
I have a branch ready for MSRV=1.21 at https://github.com/vincentdephily/stderrlog-rs/commits/update_deps_msrv and wanted to solve #20 while sticking to 1.21, but I'm struggling to find the right version pinings, so I'll switch it to 1.31 directly.

**Comment by vincentdephily** [comment]
The PR is ready for review. For reasons detailed in the commit messages, I ended up with 1.32 as a MSRV.

**Comment by cardoe** [comment]
I worked a bit backwards because I saw the -Z minimal-versions PR first and dealt with that and then pulled things up to 1.31. So now I'm cherry-picking things from your PR to bring everything to 1.31.0 to maintain compat with the log crate.

**Comment by cardoe** [comment]
This should be fixed with the changes in master. Please confirm and I'll make a 0.5.0 release.
