### ISSUE TITLE
Display logging message location

### ISSUE THREAD

**Issue by spack971** [cardoe/stderrlog-rs#26]
Hi,

Would it be possible to add a configuration option to display the message emitter location?

In Python for example, the following attributes are available for the format specification:

Attribute name | Format | Description
-- | -- | --
filename | `%(filename)s` | Filename portion of pathname.
funcName | `%(funcName)s` | Name of function containing the logging call.
lineno | `%(lineno)d` | Source line number where the logging call was issued (if available).

This can be useful when at the `DEBUG` or `TRACE` level so I'm wondering if there is such a thing in Rust?

**Comment by cardoe** [comment]
That metadata isn't available from [log](https://crates.io/log), you can see the metadata available which is only module and log level. https://docs.rs/log/0.4.11/log/struct.Metadata.html You'd have to have that available. So unfortunately I'll close this out until that's available in the metadata of the log crate.
