### ISSUE TITLE
Set module level verbosity without removing all other crates

### ISSUE THREAD

**Issue by msrd0** [cardoe/stderrlog-rs#30]
Using `stderrlog::new().verbosity(2)` works perfectly, it hides debug messages from hyper but allows info/warn/error messages to go through. Now, I'd like my own binary to output debug messages as well, so I tried `stderrlog::new().verbosity(2).module(module_path!()).verbosity(3)` but that made all log output from crates other than my binary disappear completely. Is there a way to do this?

**Comment by cardoe** [comment]
As you've gathered there is not. This is really out of scope of this crate which aims to be one of the "simple" loggers. Flexible per module configuration is the realm of what the more complex loggers do.
