### ISSUE TITLE
publish version 0.5.2?

### ISSUE THREAD

**Issue by wfraser** [cardoe/stderrlog-rs#41]
There are a number of changes since 0.5.1 I'd like to pick up, particularly the thread_local version bump.

Could you please publish a new version to crates.io?

Thanks!

**Comment by gilescope** [comment]
that would be a cool thing to do.

**Comment by cardoe** [comment]
So I was trying to figure out if there was a semver or MSRV change that affected us to necessitate a bump to 0.6.0 or 0.5.2

**Comment by cardoe** [comment]
Thanks for reminding me. 0.5.2 should now be published.

**Comment by flother** [comment]
Thanks, @cardoe, much appreciated. The CHANGELOG needs updating — it still refers to v0.6.0 instead of v0.5.2.

**Comment by cardoe** [comment]
Thanks. Done.
