### ISSUE TITLE
feature request: optionally (trigger by a feature) add #[clap(value_enum)] for timestamp

### ISSUE THREAD

**Issue by leoleoasd** [cardoe/stderrlog-rs#42]
feature request: optionally (trigger by a feature) add #[clap(value_enum)] for timestamp

**Comment by cardoe** [comment]
Can you give some more context to "trigger by a feature"? Are you wanting this to optionally depend on clap 3 so that we can have #[clap(value_enum)] on the enum?

**Comment by cardoe** [comment]
Please re-open when you can clarify what the request is.
