### ISSUE TITLE
This project is no longer maintained?

### ISSUE THREAD

**Issue by natir** [cardoe/stderrlog-rs#48]
Hello,

I find this project very useful, but it also seems to me not to be maintained anymore. There are two pull requests that seem essential to me that are waiting to be integrated.

I understand that @cardoe  is not necessarily the time to take care of this project. I would like to know if you still plan to take care of it and if not I just want say could become the maintainer of this project.

Thank for your work.

**Comment by cardoe** [comment]
I use the project actively. It compiles just fine in current Rust and in old Rust. The two open PRs are:
- updating the examples to a newer version of clap, which breaks the MSRV guarantee of the current version. Which would involve changing the semver. It doesn't seem that important to break semver over an example.
- breaking semver to grab in a newer version of chrono for an issue that's been talked about in other issues and other PRs and was determined to not affect this crate

So my question is which of the PRs are essential for you?

I care deeply about compatibility and semver support so I don't just merge things in on a whim.

**Comment by cardoe** [comment]
In fact both PRs at present fail CI so there's nothing to merge currently.

**Comment by cardoe** [comment]
I'm going to close this out. If you have any follow up please post it and feel free to re-open. Thanks.

**Comment by natir** [comment]
I'm sorry if I seemed aggressive when I opened this issue and for my huge response time.

It's ok if I work on these pull request?
