### ISSUE TITLE
Consider replacing the dependency on `atty` with `is-terminal`

### ISSUE THREAD

**Issue by AlexTMjugador** [cardoe/stderrlog-rs#56]
Hey, thanks for maintaining this useful crate!

`atty` is unmaintained and has an unresolved security advisory, [RUSTSEC-2021-0145](https://rustsec.org/advisories/RUSTSEC-2021-0145), which may affect Windows users that use a custom global allocator.

This security advisory is reported by several dependency analysis tools, and this crate has no strong functional reason to prefer `atty` over alternatives such as [`is-terminal`](https://crates.io/crates/is-terminal).

However, the latest `is-terminal` release has a MSRV of 1.48, which [might cause semver-related concerns](https://github.com/cardoe/stderrlog-rs/issues/48#issuecomment-1295351371). (By the way, bumping MSRV is usually not considered a semver-breaking change in the Cargo ecosystem, but there are different views on this and definitely no universal consensus.)

I thought about opening a PR to make this change, but I figured it would be better to discuss this change with the repository maintainer. Would bumping MSRV be acceptable here? Should we specify an `is-terminal` version that can be pinned to support the current MSRV requirement, assuming it even exists?

**Comment by cardoe** [comment]
Sure, I'd take a PR. 

I do disagree with the free wheeling approach to the stdlib/compiler dependency while everything else gets versioned. But that's a topic for another time and place.

**Comment by cardoe** [comment]
Fixed with #56
