### ISSUE TITLE
Update to log 0.4.x

### ISSUE THREAD

**Issue by remexre** [cardoe/stderrlog-rs#8]
log 0.4 is now out.

**Comment by cardoe** [comment]
@ndarilek and @JP-Ellis are hitting issues related to this.

**Comment by cardoe** [comment]
fwiw, I have released `0.4.0`. I had hoped to get some review and/or feedback on the project in my post at https://internals.rust-lang.org/t/looking-for-an-eval-of-stderrlog/7391 but didn't get any.
